version: "3.8"
services:
  server:
    container_name: RevixirBackend
    build: .
    volumes:
      - /var/www/vendor
      - .:/var/www
    ports:
      - "8000:8000"

  mssql:
    container_name: SQL_Svr
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456789"
    ports:
      - 1433:1433
    volumes:
      - ./mssql/data:/var/opt/mssql/data

networks:
  app_network:
    driver: bridge
